include:
  - remote: 'https://raw.githubusercontent.com/uker-troi-lab/misc/main/ci/.gitlab-ci.yml'

stages:
  - unittest
  - linter
  - formatter

unittest:
  extends: .unittest_template
  stage: unittest

linter:
  extends: .linter_template
  stage: linter

formatter:
  extends: .formatter_template
  stage: formatter
