default_install_hook_types:
  - pre-commit
  - commit-msg
  - post-commit
  - pre-push

repos:
  - repo: https://github.com/uker-troi-lab/commit_hooks
    rev: v0.4.3
    hooks:
      - id: troi-lab-base-hooks
      - id: check-python-dependencies
      - id: check-commit-msg
      - id: recreate-changelog
      - id: bump-version
      - id: bump-version-tag-pusher
